name: GitHub Actions Demo

run-name: ${{ github.actor }} is testing out GitHub Actions 🚀

on:
  push:
    branches:
      - main

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "event name - ${{ github.event_name }}"
      - run: echo "runner os - ${{ runner.os }}"
      - run: echo "ref - ${{ github.ref }}, repo - ${{ github.repository }}"

      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Check node version
        run: node -v

      - name: Install dependacies
        run: yarn install --frozen-lockfile

      - name: Build
        run: yarn build

      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "workspace - ${{ github.workspace }}"
      - run: echo "job's status - ${{ job.status }}"
